---
# tasks file for kerberos-client

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true

- import_tasks: init.yml

- import_tasks: install.yml

- import_tasks: configure.yml

- include_tasks: facts.yml
  when: kerberos_client__facts|bool
